---
- name: Create Resource Group
  hosts: localhost

  vars:
    rg_name: demoresourcegroup
    location: westus
    rg_state: present
    force_option: no

  tasks:

   - name: Create a resource group
     azure_rm_resourcegroup:
       name: "{{ rg_name }}"
       location: "{{ location }}"
       state: "{{ rg_state }}"
       force: "{{ force_option }}"

