---
- name: Create Resource Group
  hosts: localhost

  vars:
    rg_name: demoresourcegroup
    location: westus

  tasks:

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"
        tags:
            envrioment: testing
            delete: never